# Generated by Django 5.0.6 on 2024-09-22 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('due', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('budget', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('impact_details', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('importance', models.IntegerField()),
                ('impact', models.IntegerField()),
                ('response_status', models.TextField()),
                ('resolution', models.TextField()),
                ('date_resolved', models.CharField(max_length=50)),
                ('root_cause', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.project')),
            ],
        ),
        migrations.CreateModel(
            name='dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('due', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('budget', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.project')),
            ],
        ),
        migrations.CreateModel(
            name='decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('due', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('decision_made', models.CharField(max_length=50)),
                ('justification', models.TextField()),
                ('impact', models.TextField()),
                ('importance', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.project')),
            ],
        ),
        migrations.CreateModel(
            name='assumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('item', models.TextField()),
                ('notes', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.project')),
            ],
        ),
        migrations.CreateModel(
            name='action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('due_date', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('action_source', models.CharField(max_length=50)),
                ('importance', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.project')),
            ],
        ),
        migrations.CreateModel(
            name='risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('probability', models.IntegerField()),
                ('impact', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_raised', models.CharField(max_length=50)),
                ('trigger_date', models.CharField(max_length=50)),
                ('date_closed', models.CharField(max_length=50)),
                ('response_strategy', models.CharField(max_length=50)),
                ('response_plan_state', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.project')),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.project')),
            ],
        ),
        migrations.CreateModel(
            name='RiskTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.risk')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.tag')),
            ],
        ),
        migrations.CreateModel(
            name='IssueTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.issue')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.tag')),
            ],
        ),
        migrations.CreateModel(
            name='DependencyTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.dependency')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.tag')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.decision')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.tag')),
            ],
        ),
        migrations.CreateModel(
            name='AssumptionTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.assumption')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ActionTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.action')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.tag')),
            ],
        ),
        migrations.CreateModel(
            name='user_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
