# Generated by Django 5.0.6 on 2024-09-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidlogix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='created',
            field=models.DateField(default='2024-09-14'),
        ),
        migrations.AddField(
            model_name='action',
            name='due_date',
            field=models.DateField(default='2024-09-14'),
        ),
        migrations.AddField(
            model_name='assumption',
            name='created',
            field=models.DateField(default='2024-09-14'),
        ),
        migrations.AddField(
            model_name='decision',
            name='created',
            field=models.DateField(default='2024-09-14'),
        ),
        migrations.AddField(
            model_name='decision',
            name='due',
            field=models.DateField(default='2024-09-14'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='due',
            field=models.DateField(default='2024-09-14'),
        ),
        migrations.AddField(
            model_name='issue',
            name='created',
            field=models.DateField(default='2024-09-14'),
        ),
        migrations.AddField(
            model_name='issue',
            name='date_resolved',
            field=models.DateField(default='2024-09-14'),
        ),
        migrations.AddField(
            model_name='project',
            name='due',
            field=models.DateField(default='2024-09-14'),
        ),
        migrations.AddField(
            model_name='risk',
            name='created',
            field=models.DateField(default='2024-09-14'),
        ),
        migrations.AddField(
            model_name='risk',
            name='date_closed',
            field=models.DateField(default='2024-09-14'),
        ),
        migrations.AddField(
            model_name='risk',
            name='date_raised',
            field=models.DateField(default='2024-09-14'),
        ),
        migrations.AddField(
            model_name='risk',
            name='trigger_date',
            field=models.DateField(default='2024-09-14'),
        ),
    ]
