# Generated by Django 5.0.6 on 2024-07-11 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidlogix', '0002_employee_action_assumption_decision_issue_risk'),
    ]

    operations = [
        migrations.CreateModel(
            name='action_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.action')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.tag')),
            ],
        ),
        migrations.CreateModel(
            name='assumption_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.assumption')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.tag')),
            ],
        ),
        migrations.CreateModel(
            name='decision_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.decision')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.tag')),
            ],
        ),
        migrations.CreateModel(
            name='dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('due', models.DateField()),
                ('description', models.TextField()),
                ('budget', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.project')),
            ],
        ),
        migrations.CreateModel(
            name='employee_decisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.decision')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.employee')),
            ],
        ),
        migrations.CreateModel(
            name='employee_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.project')),
            ],
        ),
        migrations.CreateModel(
            name='issue_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.issue')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.tag')),
            ],
        ),
        migrations.CreateModel(
            name='risk_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.risk')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.tag')),
            ],
        ),
    ]
