# Generated by Django 5.0.6 on 2024-09-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidlogix', '0003_alter_action_created_alter_action_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.TextField(),
        ),
    ]
