# Generated by Django 5.0.6 on 2024-09-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidlogix', '0003_action_tags_assumption_tags_decision_tags_dependency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
