# Generated by Django 5.0.6 on 2024-09-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidlogix', '0004_alter_project_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='created',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='action',
            name='due_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='assumption',
            name='created',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='decision',
            name='created',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='decision',
            name='due',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='due',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='date_resolved',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='risk',
            name='created',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='risk',
            name='date_closed',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='risk',
            name='date_raised',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='risk',
            name='trigger_date',
            field=models.CharField(max_length=50),
        ),
    ]
