# Generated by Django 5.0.6 on 2024-09-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidlogix', '0005_alter_action_created_alter_action_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='score',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
