# Generated by Django 5.0.6 on 2024-09-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidlogix', '0007_alter_risk_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
