# Generated by Django 5.0.6 on 2024-09-19 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raidlogix', '0008_alter_risk_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assumption',
            name='updated',
        ),
    ]
