# Generated by Django 5.0.6 on 2024-09-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidlogix', '0009_remove_assumption_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='budget',
            field=models.CharField(max_length=50),
        ),
    ]
