# Generated by Django 5.0.6 on 2024-09-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raidlogix', '0010_alter_dependency_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_decisions',
        ),
    ]
