# Generated by Django 5.0.6 on 2024-09-20 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidlogix', '0011_delete_user_decisions'),
    ]

    operations = [
        migrations.CreateModel(
            name='dependency_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.dependency')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raidlogix.tag')),
            ],
        ),
    ]
