version: '3.8'

services:
  web:
    build: .  # Use the current directory containing the Dockerfile
    ports:
      - "8000:8000"
      - ""  # Map port 8000 on the host to port 8000 in the container
    volumes:
      - .:/raidapp  # Mount the current directory to /raidapp in the container
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    expose:
      - "8000"
    command: python manage.py runserver 0.0.0.0:8000
    
